main: com.therealspoljo.smelter.Main
name: Smelter
version: 3.0.0
author: therealspoljo
softdepend: [Vault]
api-version: 1.17

commands:
  smelt:
    description: Smelts item from your hands
    usage: /<command>
    aliases: []
  smeltall:
    description: Smelts all smeltable items from your inventory
    usage: /<command>
    aliases: []
  smelter:
    description: Main command
    usage: /<command> <reload(rl)>
    aliases: []

permissions:
  smelter.admin:
    description: Allows you to reload config files
    default: op
  smelter.smelt:
    description: Allows you to use /smelt
    default: op
  smelter.smelt.free:
    description: Allows you to use /smelt without any costs
    default: op
  smelter.smelt.no-cooldown:
    description: Allows you to use /smelt without a cooldown
    default: op
  smelter.smeltall:
    description: Allows you to use /smeltall
    default: op
  smelter.smeltall.free:
    description: Allows you to use /smeltall without any costs
    default: op
  smelter.smeltall.no-cooldown:
    description: Allows you to use /smeltall without a cooldown
    default: op